FROM python:3.11-slim

ARG TARGETPLATFORM

RUN apt update && apt install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    git && \
    apt clean && \
    rm -rf /var/lib/apt/list/*


WORKDIR /home/worker/app

RUN git clone https://github.com/zylon-ai/private-gpt .
RUN sed -i -e 's/http:\/\/localhost:11434/$\{OLLAMA_BASE_URL\}/g' settings-ollama.yaml
RUN pip install pipx
RUN python -m pipx ensurepath
RUN pipx install poetry

ENV PATH="/root/.local/bin:$PATH"
ENV PATH=".venv/bin/:$PATH"
ENV OLLAMA_BASE_URL="http://ollama:11434"
ENV PGPT_PROFILES="ollama"
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
RUN poetry install --extras "ui llms-ollama embeddings-ollama vector-stores-qdrant"
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="$PYTHONPATH:/private_gpt/"
ENV PORT=8080

EXPOSE 8080

ENTRYPOINT python -m private_gpt